#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh psx.ps.h /Tps_3_0 ps_psx.hlsl
//
//
// Parameters:
//
//   bool b_mul_tex;
//   sampler2D tex0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   b_mul_tex    b0       1
//   tex0         s0       1
//

// Shader type: pixel 

xps_3_0
defconst b_mul_tex, bool, scalar, [1, 1], b0
defconst tex0, sampler2d, object, [1, 1], s0
config AutoSerialize=false
config AutoResource=false
config PsMaxReg=1
// PsExportColorCount=1
// PsSampleControl=both

dcl_texcoord r0.xy
dcl_color_centroid r1


    exec
    tfetch2D r0.zyx_, r0.xy, tf0
    alloc colors
    cjmp !b128, L5
    exec
    mul r1.xyz, r0.zyx, r1.xyz
    jmp L6
label L5
    exec
    add r1.xyz, r0.zyx, r1.xyz
label L6
    exece
    mov oC0, r1

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xps_main[] =
{
    0x102a1100, 0x000000dc, 0x0000006c, 0x00000000, 0x00000024, 0x00000000, 
    0x000000b4, 0x00000000, 0x00000000, 0x0000008c, 0x0000001c, 0x0000007f, 
    0xffff0300, 0x00000002, 0x0000001c, 0x00000000, 0x00000078, 0x00000044, 
    0x00000000, 0x00010000, 0x00000050, 0x00000000, 0x00000060, 0x00030000, 
    0x00010000, 0x00000068, 0x00000000, 0x625f6d75, 0x6c5f7465, 0x7800abab, 
    0x00000001, 0x00010001, 0x00010000, 0x00000000, 0x74657830, 0x00ababab, 
    0x0004000c, 0x00010001, 0x00010000, 0x00000000, 0x70735f33, 0x5f300032, 
    0x2e302e32, 0x30333533, 0x2e3000ab, 0x00000000, 0x0000006c, 0x10000100, 
    0x00000008, 0x00020000, 0x00001842, 0x00010003, 0x00000001, 0x00003050, 
    0x0000f1a0, 0x00011004, 0x00001200, 0xc4000000, 0x00000005, 0x1005b200, 
    0x12000000, 0x00002006, 0x1006b000, 0x12000000, 0x00001007, 0x00002200, 
    0x00000000, 0x10080001, 0x1f1ffe0a, 0x00004000, 0xc8070001, 0x0062c000, 
    0xe1000100, 0xc8070001, 0x0062c000, 0xe0000100, 0xc80f8000, 0x00000000, 
    0xe2010100, 0x00000000, 0x00000000, 0x00000000
};
