#if 0
//
// Generated by 2.0.20353.0
//
//   fxc /Fh scale2x.vs.h /Tvs_3_0 Scale2xPlus.fx /EVS
//
//
// Parameters:
//
//   float2 texture_size;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   texture_size c0       1
//

// Shader type: vertex 

xvs_3_0
defconst texture_size, float, vector, [1, 2], c0
config AutoSerialize=false
config AutoResource=false
config VsMaxReg=1
config VsResource=1
// VsExportCount=2

dcl_index r0.x
dcl_texcoord o0.xy
dcl_texcoord1 o1
dcl_texcoord2 o2


    exec
    vfetch r1, r0.x, position
    vfetch r0.xy__, r0.x, texcoord
    alloc position
    exec
    mov oPos, r1
    alloc interpolators
    exec
    rcp r0.z, c0.y
    rcp r0.w, c0.x
    mov o0.xy, r0.xy
    mov o1.xw, r0.xy
    add o1.yz, -r0.zzw, r0.yyx
    add r0.zw, r0.wwwz, r0.xxxy
    exece
    mov o2, r0.zyxw

// PDB hint 00000000-00000000-00000000

#endif

// This microcode is in native DWORD byte order.

const DWORD g_xvs_VS[] =
{
    0x102a1101, 0x000000d8, 0x000000a8, 0x00000000, 0x00000024, 0x00000000, 
    0x0000008c, 0x00000000, 0x00000000, 0x00000064, 0x0000001c, 0x00000057, 
    0xfffe0300, 0x00000001, 0x0000001c, 0x00000000, 0x00000050, 0x00000030, 
    0x00020000, 0x00010000, 0x00000040, 0x00000000, 0x74657874, 0x7572655f, 
    0x73697a65, 0x00ababab, 0x00010003, 0x00010002, 0x00010000, 0x00000000, 
    0x76735f33, 0x5f300032, 0x2e302e32, 0x30333533, 0x2e3000ab, 0x00000000, 
    0x000000a8, 0x00210001, 0x00000000, 0x00000000, 0x00002863, 0x00000001, 
    0x00000002, 0x00000004, 0x00000290, 0x00100003, 0x00305004, 0x00003050, 
    0x0001f151, 0x0003f252, 0x00001008, 0x00000009, 0x0000100a, 0x0000100c, 
    0x30052003, 0x00001200, 0xc2000000, 0x00001005, 0x00001200, 0xc4000000, 
    0x00006006, 0x100c1200, 0x22000000, 0x05f81000, 0x00000688, 0x00000000, 
    0x05f80000, 0x00000fc8, 0x00000000, 0xc80f803e, 0x00000000, 0xe2010100, 
    0x4c400000, 0x000000b1, 0xc2000000, 0x4c800000, 0x0000006c, 0xc2000000, 
    0xc8038000, 0x00b0b000, 0xe2000000, 0xc8098001, 0x00b0b000, 0xe2000000, 
    0xc8068001, 0x04166100, 0xe0000000, 0xc80c0000, 0x00dbac00, 0xe0000000, 
    0xc80f8002, 0x00222200, 0xe2000000, 0x00000000, 0x00000000, 0x00000000
};
